CREATE TABLE IF NOT EXISTS catalog_sync_checkpoints (
  source_name TEXT NOT NULL,
  source_entity_type TEXT NOT NULL,
  media_type TEXT NOT NULL,
  next_page INTEGER NOT NULL DEFAULT 1,
  per_page INTEGER NOT NULL,
  last_processed_source_id BIGINT,
  total_pages_processed INTEGER NOT NULL DEFAULT 0,
  total_records_processed BIGINT NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'idle',
  failure_count INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  started_at TIMESTAMPTZ,
  last_requested_at TIMESTAMPTZ,
  last_completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (source_name, source_entity_type, media_type),
  CHECK (source_name <> ''),
  CHECK (source_entity_type <> ''),
  CHECK (media_type <> ''),
  CHECK (next_page >= 1),
  CHECK (per_page BETWEEN 1 AND 50),
  CHECK (status IN ('idle', 'running', 'failed', 'completed')),
  CHECK (failure_count >= 0)
);
